[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#0c0200"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f82b06"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"